### ISSUE TITLE
Take a picture of medical document

### ISSUE THREAD

**Issue by ghiobi** [imbaky/PatientFocus#1]
## User Story

As a patient, I can upload a picture of my document by from my phone.

## Tasks Breakdown
- [x] **(if not created)** Create Document page (and add to menu)
- [x] **(if not created)** Create button to add document

## Acceptance Criteria
- [ ] The user can see a button to add new medical documents.
- [ ] The user can upload a picture from their phone's camera.
- [ ] The picture is added in the document folder in the file system
