### ISSUE TITLE
Schedule appointments

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#11]
## User Story
As a patient, I want to be able to schedule health appointments 

## Tasks Breakdown
- [x] Create appointment types
- [x] Add schedule to UI
- [x] Save appointment to database
- [x] Add edit appointment
- [x] Add delete appointment
- [x] Write tests
- [x] Add schedule appointment to notification

## Acceptance Criteria.
- [x] User can create, edit, delete appointment
- [x] User is notified of appointment
