### ISSUE TITLE
Set reminders to take medication

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#12]
## User Story
As a patient, I want to be able to set reminders to take medication

<!---
## Mockups
![Mockup](https://www.webpagefx.com/blog/images/assets/cdn.sixrevisions.com/0486-01-mockup-fidelity-progression.png)

## Tasks Breakdown
- [x] add the Add button (maybe make component)
- [x] create form
- [x] add profile
- [x] display reminder
- [x] delete reminder
- [x] write notification service
- [x] save to database (local notifications might do this)
- [x] test notifications

## Acceptance Criteria.
- [ ] Can enter medication and dosage
- [ ] Can set times per day
- [ ] Can set start time
- [ ] Can expiry date
- [ ] Can delete reminder
