### ISSUE TITLE
Patient medical information to profile

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#13]
## User Story
As a patient, I would like to add my medical information (Blood type, previous medical problems, allergies, surgeries..etc) so that it can be shared with the doctor easily.

## Mockups

![menu](https://user-images.githubusercontent.com/6955509/34929412-b2a607f8-f991-11e7-9db1-92a6ccf7e362.jpg)

![page_1 3](https://user-images.githubusercontent.com/6955509/34929385-92875634-f991-11e7-9129-07e41fb3a855.png)

## Tasks Breakdown
- [x] Update hamburger menu
- [x] Update dexie schema for profile
- [x] Create new schema and services for medical info and emergency contact
- [x] Create profile info page
- [x] Display various info on the view
- [x] Change info section to form when editing
- [x] Save changes to dexie

## Acceptance Criteria.
- [x] User clicks on hamburger menu and sees his name and a placeholder image
- [x] Clicking the image sends user to Profile info page
- [x] Profile info page contains **Personal Info**, **Medical Info**, and **Emergency Contact** sections
- [x] Info sections are editable
