### ISSUE TITLE
Import a file from my phone's internal storage

### ISSUE THREAD

**Issue by ghiobi** [imbaky/PatientFocus#2]
## User Story

As a patient, I can import a file with my medical document from my phone's internal storage.

## Acceptance Criteria
- [x] The user can see a button to add new medical documents.
- [x] The user selects the type of document they are importing. For now, we will have Lab Tests, Image Report, Consultation reports, Discharge summaries, and Prescription.
- [x] The user can select an effective date (in this case, date in which the document should be placed)
- [x] The user can import a file from their phone's internal storage to our application's file system.
_____
**Accepted formats:**
- [x]  `.pdf`
- [x]  `.txt`
- [x] `.jpg`
- [x]  `.png`
_____
**Tasks:**
- [x] Create import document modal
- [x] Create date selector component
- [x] Create file selector component
- [x] Selected file is copied to the appropriate app-specific data files' directory
- [x] Create document-type selector component
- [x] Create upload service (in parallel with #1)
- [ ] Write tests for document import
- [ ] Write tests for document date
- [ ] Style user interface components

## Mockups
![Mockup](https://github.com/imbaky/PatientFocus/wiki/images/2.png)
