### ISSUE TITLE
View a list of medical documents

### ISSUE THREAD

**Issue by ghiobi** [imbaky/PatientFocus#3]
## User Story
As a patient, I would like to view a list of my medical documents.

## Tasks
- [x] install necessary libraries for database and data storage.

## Acceptance Criteria.
_______
**Given that:**
- Patient imported at least one medical document to their account.
- Patient has navigated to the Documents Tab
______
- [x] A list of documents is displayed
- [x] Each document type is displayed ( lab tests, imaging reports...etc)
- [x] Each file format is displayed (pdf, txt, jpg, png, etc...)
- [x] Date the document was added

## Tasks
- [x] integrate dexie and momentjs #19 
- [x] create models for a filestructure. #21
- [x] create file navigational views

## Mockups
![Mockup](https://github.com/imbaky/PatientFocus/wiki/images/Documents.png)
