### ISSUE TITLE
Timeline 

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#49]
## User Story
As a user, I want to be able to see a timeline that contains all the documents in the Portfolio and the Entries in my diary, ordered by date.

## Tasks Breakdown
- [ ] Refactor portfolio module to extract logic outside the page
- [ ] Create Timeline module
- [ ] Create Dashboard Page that includes the Timeline module

## Acceptance Criteria.
Given that:
- The user has a portfolio

- [ ] If the user has a document, it should appear on the timeline in chronological order. 
- [ ] If the user has a diary entry, it should appear on the timeline in chronological order.
