### ISSUE TITLE
Patient adds diary entry

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#6]
## User Story

As a patient, I would like to add diary entry (i.e glucose reading, blood pressure, missed medication, bumped head, take pictures of my skin infections)

## Mockups
![android mobile 1](https://user-images.githubusercontent.com/6437556/34922671-1a6ef100-f961-11e7-906e-8b4c568485fc.png)
![android mobile 2](https://user-images.githubusercontent.com/6437556/34922670-1a56d9b2-f961-11e7-8181-13d0efb92783.png)
![android mobile 3](https://user-images.githubusercontent.com/6437556/34922669-1a2fbaee-f961-11e7-887d-31917fbd115f.png)

## Tasks Breakdown
- [ ] Update Dexie schema to accept patient diary
- [ ] Create a Diary Service which handles persistence layer operations
- [ ] Create a Diary module
- [ ] Create a Diary page component which will accept the following patient input: title, date, description, and image (optional).

## Acceptance Criteria.
- [ ]  The user can access his/her diary
- [ ]  The user can view his/her diary entries as a list view. Each entry has the title, description, date and optional image.
- [ ]  The user can view details of a diary entry by tapping on it.
- [ ]  The user can add a diary entry by tapping the fab button. An entry can have a title, description, date and optional image.
