### ISSUE TITLE
Edit & Delete Diary entries

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#68]
## User Story
As a user, I want to be able to edit and delete diary entries.

## Tasks Breakdown
- [x] Create edit and remove options for diary entries
- [x] Bind medical document into a edit form
- [x] Delete file from local external Android directory
- [x] Delete file from "File" table
- [x] Delete item from "Item" table
- [x] Update view for diary entries

## Acceptance Criteria
- [] User can edit the attachment, title, or description of a diary entry
- [] User can delete a diary entry
