### ISSUE TITLE
Edit & Delete Medical documents

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#69]
## User Story
As a user, I want to be able to edit and delete existing medical documents.

## Tasks Breakdown
- [x] Create edit and remove options for medical documents
- [x] Bind medical document into a edit form
- [x] Delete file from local external Android directory
- [x] Delete file from "File" table
- [x] Delete item from "Item" table
- [x] Update directory items

## Acceptance Criteria.
Given that the user has a portfolio directory:
- [ ] The user should be able to swipe items to the left to view "Edit" and "Delete" options.
- [ ] If the user clicks "Delete", then the user will be prompted for a document removal.
- [ ] If the user clicks "Edit", then the user will view the edit form.
- [ ] If the user clicks "Edit", then the user can modify ALL fields (name, date, type, and file) with validation.
- [ ] User sees his/her portolio page updated with the expected documents.
