### ISSUE TITLE
Sharing Medical profile

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#72]
## User Story
As a user, I want to be able to share my medical profile with my doctor.

<!---
## Mockups
![Mockup](https://www.webpagefx.com/blog/images/assets/cdn.sixrevisions.com/0486-01-mockup-fidelity-progression.png)

## Tasks Breakdown
- [x] need to do https (ionic plugin does not support)
- [ ] need to create temp url
- [ ] need to be able to copy shared documents to shared folder
- [ ] clean shared folder
- [ ] need to set header to not cache
- [ ] need disclaimer popup
- [ ] write tests

## Acceptance Criteria.
- [ ] Can copy files to shared folder
- [ ] Doctor can use temp url to view documents
- [ ] Must have the disclaimer
