### ISSUE TITLE
Filter Diary Entries

### ISSUE THREAD

**Issue by imbaky** [imbaky/PatientFocus#83]
## User Story
As a user, I want to be able to filter diary entries

## Tasks Breakdown
- [x] Create pipe if needed
- [x] Add filter option to html
- [x] Filter by date
- [x] Filter by word(s)
- [x] Write tests

## Acceptance Criteria.
- [ ] Can filter by date
- [ ] Can filter by search term
